GET http://localhost:3000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNmQxNDU1Ny05ZjhkLTRmM2MtOTEzMS1kZmYyNTg5OTM5ZjciLCJpYXQiOjE2NDg2NjE2NzAsImV4cCI6MTY0ODc0ODA3MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwLyJ9.cg68oo2UwSToa8I3lKVrgfA3sCqvH3Hl2PZeazHxBz4yTp_HBx2Dc0RhIKMFC_FyMV51qRhmwyuRx_ZRXfmtUw